package wolf.cfg.hbm;

// Generated 2014-2-15 20:31:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Chat generated by hbm2java
 */
public class Chat implements java.io.Serializable {

	private String elchId;
	private String elcourseId;
	private String elchName;
	private String elchUrl;
	private Date elchTime;
	private String elchReverse1;//是否允许回复
	private String elchReverse2;//是否删除

	public Chat() {
	}

	public Chat(String elchId) {
		this.elchId = elchId;
	}

	public Chat(String elchId, String elcourseId, String elchName,
			String elchUrl, Date elchTime, String elchReverse1,
			String elchReverse2) {
		this.elchId = elchId;
		this.elcourseId = elcourseId;
		this.elchName = elchName;
		this.elchUrl = elchUrl;
		this.elchTime = elchTime;
		this.elchReverse1 = elchReverse1;
		this.elchReverse2 = elchReverse2;
	}

	public String getElchId() {
		return this.elchId;
	}

	public void setElchId(String elchId) {
		this.elchId = elchId;
	}

	public String getElcourseId() {
		return this.elcourseId;
	}

	public void setElcourseId(String elcourseId) {
		this.elcourseId = elcourseId;
	}

	public String getElchName() {
		return this.elchName;
	}

	public void setElchName(String elchName) {
		this.elchName = elchName;
	}

	public String getElchUrl() {
		return this.elchUrl;
	}

	public void setElchUrl(String elchUrl) {
		this.elchUrl = elchUrl;
	}

	public Date getElchTime() {
		return this.elchTime;
	}

	public void setElchTime(Date elchTime) {
		this.elchTime = elchTime;
	}

	public String getElchReverse1() {
		return this.elchReverse1;
	}

	public void setElchReverse1(String elchReverse1) {
		this.elchReverse1 = elchReverse1;
	}

	public String getElchReverse2() {
		return this.elchReverse2;
	}

	public void setElchReverse2(String elchReverse2) {
		this.elchReverse2 = elchReverse2;
	}

}
