package wolf.cfg.hbm;

// Generated 2014-2-15 20:31:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private String elcourseId;
	private String elcourseName;
	private String elcourseGroup;
	private String elcourseInfo;
	private String elcourseReverse1;
	private Date elcourseDate;
	private String elcourseTeacher;
	private String elcoursePurport;
	public Course() {
	}

	public Course(String elcourseId) {
		this.elcourseId = elcourseId;
	}

	public Course(String elcourseId, String elcourseName, String elcourseGroup,
			String elcourseInfo, String elcourseReverse1, Date elcourseDate,
			String elcourseTeacher,String elcoursePurport) {
		this.elcourseId = elcourseId;
		this.elcourseName = elcourseName;
		this.elcourseGroup = elcourseGroup;
		this.elcourseInfo = elcourseInfo;
		this.elcourseReverse1 = elcourseReverse1;
		this.elcourseDate = elcourseDate;
		this.elcourseTeacher = elcourseTeacher;
		this.elcoursePurport = elcoursePurport;
	}

	public String getElcoursePurport() {
		return elcoursePurport;
	}

	public void setElcoursePurport(String elcoursePurport) {
		this.elcoursePurport = elcoursePurport;
	}

	public String getElcourseId() {
		return this.elcourseId;
	}

	public void setElcourseId(String elcourseId) {
		this.elcourseId = elcourseId;
	}

	public String getElcourseName() {
		return this.elcourseName;
	}

	public void setElcourseName(String elcourseName) {
		this.elcourseName = elcourseName;
	}

	public String getElcourseGroup() {
		return this.elcourseGroup;
	}

	public void setElcourseGroup(String elcourseGroup) {
		this.elcourseGroup = elcourseGroup;
	}

	public String getElcourseInfo() {
		return this.elcourseInfo;
	}

	public void setElcourseInfo(String elcourseInfo) {
		this.elcourseInfo = elcourseInfo;
	}

	public String getElcourseReverse1() {
		return this.elcourseReverse1;
	}

	public void setElcourseReverse1(String elcourseReverse1) {
		this.elcourseReverse1 = elcourseReverse1;
	}

	public Date getElcourseDate() {
		return this.elcourseDate;
	}

	public void setElcourseDate(Date elcourseDate) {
		this.elcourseDate = elcourseDate;
	}

	public String getElcourseTeacher() {
		return this.elcourseTeacher;
	}

	public void setElcourseTeacher(String elcourseTeacher) {
		this.elcourseTeacher = elcourseTeacher;
	}

}
