package wolf.cfg.hbm;

// Generated 2014-2-15 20:31:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Data generated by hbm2java
 */
public class Data implements java.io.Serializable {

	private String eldtId;
	private String elcourseId;
	private String eldtName;
	private String eldtUrl;
	private Date eldtUptime;
	private Date eldtDowmtime;
	private String eldtLoader;
	private Integer eldtTimes;
	private Integer eldtDelete;

	public Data() {
	}

	public Data(String eldtId) {
		this.eldtId = eldtId;
	}

	public Data(String eldtId, String elcourseId, String eldtName,
			String eldtUrl, Date eldtUptime, Date eldtDowmtime,
			String eldtLoader, Integer eldtTimes,Integer eldtDelete) {
		this.eldtId = eldtId;
		this.elcourseId = elcourseId;
		this.eldtName = eldtName;
		this.eldtUrl = eldtUrl;
		this.eldtUptime = eldtUptime;
		this.eldtDowmtime = eldtDowmtime;
		this.eldtLoader = eldtLoader;
		this.eldtTimes = eldtTimes;
		this.eldtDelete =eldtDelete;
	}

	public Integer getEldtDelete() {
		return eldtDelete;
	}

	public void setEldtDelete(Integer eldtDelete) {
		this.eldtDelete = eldtDelete;
	}

	public String getEldtId() {
		return this.eldtId;
	}

	public void setEldtId(String eldtId) {
		this.eldtId = eldtId;
	}

	public String getElcourseId() {
		return this.elcourseId;
	}

	public void setElcourseId(String elcourseId) {
		this.elcourseId = elcourseId;
	}

	public String getEldtName() {
		return this.eldtName;
	}

	public void setEldtName(String eldtName) {
		this.eldtName = eldtName;
	}

	public String getEldtUrl() {
		return this.eldtUrl;
	}

	public void setEldtUrl(String eldtUrl) {
		this.eldtUrl = eldtUrl;
	}

	public Date getEldtUptime() {
		return this.eldtUptime;
	}

	public void setEldtUptime(Date eldtUptime) {
		this.eldtUptime = eldtUptime;
	}

	public Date getEldtDowmtime() {
		return this.eldtDowmtime;
	}

	public void setEldtDowmtime(Date eldtDowmtime) {
		this.eldtDowmtime = eldtDowmtime;
	}

	public String getEldtLoader() {
		return this.eldtLoader;
	}

	public void setEldtLoader(String eldtLoader) {
		this.eldtLoader = eldtLoader;
	}

	public Integer getEldtTimes() {
		return this.eldtTimes;
	}

	public void setEldtTimes(Integer eldtTimes) {
		this.eldtTimes = eldtTimes;
	}

}
