package wolf.cfg.hbm;

// Generated 2014-2-15 20:31:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Exercise generated by hbm2java
 */
public class Exercise implements java.io.Serializable {

	private String elexId;
	private String elcourseId;
	private String elexUrl;
	private String elexName;
	private Date elexDate;
	private String elexUsername;
	private String elexReverse1;
	private Integer elexDelete;

	public Exercise() {
	}

	public Exercise(String elexId) {
		this.elexId = elexId;
	}

	public Exercise(String elexId, String elcourseId, String elexUrl,
			String elexName, Date elexDate, String elexUsername,
			String elexReverse1,Integer elexDelete) {
		this.elexId = elexId;
		this.elcourseId = elcourseId;
		this.elexUrl = elexUrl;
		this.elexName = elexName;
		this.elexDate = elexDate;
		this.elexUsername = elexUsername;
		this.elexReverse1 = elexReverse1;
		this.elexDelete =elexDelete;
	}

	public Integer getElexDelete() {
		return elexDelete;
	}

	public void setElexDelete(Integer elexDelete) {
		this.elexDelete = elexDelete;
	}

	public String getElexId() {
		return this.elexId;
	}

	public void setElexId(String elexId) {
		this.elexId = elexId;
	}

	public String getElcourseId() {
		return this.elcourseId;
	}

	public void setElcourseId(String elcourseId) {
		this.elcourseId = elcourseId;
	}

	public String getElexUrl() {
		return this.elexUrl;
	}

	public void setElexUrl(String elexUrl) {
		this.elexUrl = elexUrl;
	}

	public String getElexName() {
		return this.elexName;
	}

	public void setElexName(String elexName) {
		this.elexName = elexName;
	}

	public Date getElexDate() {
		return this.elexDate;
	}

	public void setElexDate(Date elexDate) {
		this.elexDate = elexDate;
	}

	public String getElexUsername() {
		return this.elexUsername;
	}

	public void setElexUsername(String elexUsername) {
		this.elexUsername = elexUsername;
	}

	public String getElexReverse1() {
		return this.elexReverse1;
	}

	public void setElexReverse1(String elexReverse1) {
		this.elexReverse1 = elexReverse1;
	}

}
