package wolf.cfg.hbm;

// Generated 2014-2-15 20:31:44 by Hibernate Tools 3.2.2.GA

/**
 * UserCourseId generated by hbm2java
 */
public class UserCourseId implements java.io.Serializable {

	private String elcourseId;
	private String eluserId;

	public UserCourseId() {
	}

	public UserCourseId(String elcourseId, String eluserId) {
		this.elcourseId = elcourseId;
		this.eluserId = eluserId;
	}

	public String getElcourseId() {
		return this.elcourseId;
	}

	public void setElcourseId(String elcourseId) {
		this.elcourseId = elcourseId;
	}

	public String getEluserId() {
		return this.eluserId;
	}

	public void setEluserId(String eluserId) {
		this.eluserId = eluserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserCourseId))
			return false;
		UserCourseId castOther = (UserCourseId) other;

		return ((this.getElcourseId() == castOther.getElcourseId()) || (this
				.getElcourseId() != null && castOther.getElcourseId() != null && this
				.getElcourseId().equals(castOther.getElcourseId())))
				&& ((this.getEluserId() == castOther.getEluserId()) || (this
						.getEluserId() != null
						&& castOther.getEluserId() != null && this
						.getEluserId().equals(castOther.getEluserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getElcourseId() == null ? 0 : this.getElcourseId()
						.hashCode());
		result = 37 * result
				+ (getEluserId() == null ? 0 : this.getEluserId().hashCode());
		return result;
	}

}
