package wolf.cfg.hbm;

// Generated 2014-2-15 20:31:44 by Hibernate Tools 3.2.2.GA

/**
 * UserCourse generated by hbm2java
 */
public class UserCourse implements java.io.Serializable {

	private UserCourseId id;

	public UserCourse() {
	}

	public UserCourse(UserCourseId id) {
		this.id = id;
	}

	public UserCourseId getId() {
		return this.id;
	}

	public void setId(UserCourseId id) {
		this.id = id;
	}

}
